### ISSUE TITLE
ESP32 not connect ESP01

### ISSUE THREAD

**Issue by thanhhuyen6sdghsjdgq** [RomanLut/hx_espnow_rc#13]
I have tried using ESp32 as controller and loading code rx_esp01_sbus for esp01 but i am having problem that they cannot connect to each other

**Comment by RomanLut** [comment]
What code is flashed to esp32?

**Comment by thanhhuyen6sdghsjdgq** [comment]
I flashed it with the code tx_diy_controller

**Comment by RomanLut** [comment]
Please provide  teminal output from esp32.

**Comment by thanhhuyen6sdghsjdgq** [comment]
esp32 got wifi but esp01 failed to connect to wifi "hxrct"

**Comment by RomanLut** [comment]
"espnow_long_range_mode": false,
- should be false in active profile in order to allow esp01 to connect to esp32.

**Comment by nopi890** [comment]
Saya memflash esp32 dengan kode tx DIY controller tapi muncul error' xtensa/hal.h no such file or directory

**Comment by RomanLut** [comment]
There is probably some problem with Platformio/SDK installation
https://community.platformio.org/t/after-update-compile-error-in-library/29625/3

**Comment by nopi890** [comment]
Saran anda sudah saya lakukan tapi eror tetap ada

**Comment by nopi890** [comment]
![Uploading IMG_20240106_184500.jpg…]()

**Comment by RomanLut** [comment]
I am sorry this error is not related to hx_espnow_rc project, but to PlatformIO installation. I can not help with that.
