### ISSUE TITLE
many TX and RX in one area?

### ISSUE THREAD

**Issue by AutoPlantBali** [RomanLut/hx_espnow_rc#15]
Hello..
allows more than one TX and RX in the same area? and can the SSID TX and RX be changed?

**Comment by RomanLut** [comment]
Yes, you have to change USE_KEY no any unique number 0....65535 on receiver and transmitter.
https://github.com/RomanLut/hx_espnow_rc/blob/985f6f78779cb80554b30bbffa7cdd135ff7087c/examples/rx_d1_mini_sbus/include/rx_config.h#L32C1-L33C19

SSID can be changed too, but it is used for OTA updating only and has no relation to RC Link.
https://github.com/RomanLut/hx_espnow_rc/blob/985f6f78779cb80554b30bbffa7cdd135ff7087c/examples/rx_d1_mini_sbus/src/main.cpp#L58
