### ISSUE TITLE
Transmitter ACK timeout

### ISSUE THREAD

**Issue by tomtomic** [RomanLut/hx_espnow_rc#22]
Hello,

i'm waiting for my esp32 board and playing with diy controler on esp32s2mini with old  slow oled.
Due to oled and esp32s2 i found a problem with waiting for ack on TX.
Loop on TX is too lazy and ack from RX is probably missed - mostly if TX plays audio (low_battery - i don't have a voltage divider yet).
RX and TX are still running, but there is still failsafe and no packet transfer until i reboot TX.
It usually occurs after about 1/2 hour, sometimes later.
But my hw conditions are not typical for flying.

I added ACK timeout in ESPNOW-Master as you have in Slave and then TX and RX communicate continously for over 3 hours with only 4 ack timeouts logged.

My code in HX_ESPNOW_RC_Master.cpp
If you want you can improve the stability
![image](https://github.com/RomanLut/hx_espnow_rc/assets/101948487/c0fd3cca-46f5-4928-a5ae-b7713aac3f07)

btw: thanks for a nice project
Tomas

**Comment by RomanLut** [comment]
Thanks, added to master.
